### ISSUE TITLE
feliz cumpleaños

### ISSUE THREAD

**Issue by carloxavier** [marton987/django-gateway#1]
@marton987 te mando un ticket de feliz cumple bro, porque los devs nunca tenemos suficientes issues 😂 
saludos y un abrazo!

P.S.: epic dummy issue just solved by itself

**Comment by marton987** [comment]
Hahaha chamo, no sé por qué me llegó la notificación hoy!! 😃 

Muchas gracias mi pana! 

¿Debería de hacer un PR con mi respuesta 🤔 ?
